Potatiki 1.1 add styles
frontend-park-mail-ru/2023_2_Potatiki pull request #1
Opened 2023-09-29 17:48 UTC by khristina455

2023-09-30 08:46 UTC, tUnknownLegend requested changes
Хорошая работа, но есть некоторые недочеты. Часто проблемы однотипные, на каждое повторение часто коммент не писал, но вас попрошу поправить везде. Если не очень понятно в чем проблема или есть какие-то вопросы - заходите в лс)

2023-09-30 08:46 UTC, tUnknownLegend commented on public/src/components/carousel/carousel.css
> +.carousel__button > img {
почему бы просто не воспользоваться классом на img? Для того чтобы разобраться в чем тут проблема советую почитать про [скорость селекторов](https://csswizardry.com/2011/09/writing-efficient-css-selectors/). Кроме того такие селекторы повышают связность css с структурой html - если поменяется html, придется менять и css

2023-09-30 08:46 UTC, tUnknownLegend commented on public/src/components/form/form.js
> +    self.innerHTML = '';
кажется, что там и так пусто

2023-09-30 08:46 UTC, tUnknownLegend commented on public/src/components/input/input.hbs
> +    {{#if label}}<label class="{{labelClass}}" for="{{labelFor}}">{{labelText}}</label>{{/if}}
можно убрать отдельный параметр label и проверять на наличие labelClass

2023-09-30 08:46 UTC, tUnknownLegend commented on public/src/components/input/input.hbs
> +    {{#if error}}<div class="{{inputError}}">{{errorText}}</div>{{/if}}
аналогично можно убрать error

2023-09-30 08:46 UTC, tUnknownLegend commented on public/src/components/loginForm/loginForm.hbs
> +<form class="login-form" id="login-form" method="post" name="{{formName}}" novalidate>
у вас был компонент form. Теперь появляется loginForm никак не связанный с form. Давайте либо их свяжем, либо какой-то из них уберем

2023-09-30 08:46 UTC, tUnknownLegend commented on public/src/components/searchForm/searchForm.hbs
> +<form class="search-form" id="search-form" method="post" name="{{formName}}" novalidate>
еще одна версия формы)

2023-09-30 08:46 UTC, tUnknownLegend commented on public/src/components/signupForm/signupForm.hbs
> +<form class="signup-form" id="signup-form" method="post" name="{{formName}}" novalidate>
и еще одна)

2023-09-30 08:46 UTC, tUnknownLegend commented on public/src/pages/login-page/login-page.js
> +    form.elements.login.value = '';
кажется, что логин точно сбрасывать не надо

2023-09-30 08:46 UTC, tUnknownLegend commented on public/src/pages/login-page/login-page.js
> +    if (password !== 'password') {
не забывайте убрать моки)

2023-09-30 08:46 UTC, tUnknownLegend commented on public/src/pages/login-page/login-page.js
> +      newConfig.inputs.password = passwordErrConfig;
не очень понял зачем нужен passwordErrConfig, поясните, пожалуйста. Если хотели сделать копию, то Object.assign - [не самый безопасный вариант](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#warning_for_deep_clone)

2023-09-30 08:46 UTC, tUnknownLegend commented on public/src/pages/login-page/login-page.js
> +    this.#parent.insertAdjacentHTML('beforeend', window.Handlebars.templates['login-page.hbs']());
почему бы сразу не положить в innerHTML?

2023-09-30 08:46 UTC, tUnknownLegend commented on public/src/pages/main-page/main-page.js
> +     * @param {*} parent
круто, что начали JSDoc!

2023-09-30 13:17 UTC, khristina455 commented on public/src/components/carousel/carousel.css
> +.carousel-name {
меня заклинило и я перепутала обозначения, поменяла на элемент

2023-09-30 13:59 UTC, khristina455 commented on public/src/components/button/button.hbs
> +<button class="button {{class}}" type="{{type}}" id="{{id}}">
в форме же используется type submit? а просто пустым нельзя оставлять id? или пустая строка тоже считается значением id

2023-10-01 17:58 UTC, tUnknownLegend commented on public/src/components/button/button.hbs
> +<button class="button {{class}}" type="{{type}}" id="{{id}}">
> в форме же используется type submit? а просто пустым нельзя оставлять id? или пустая строка тоже считается значением id

можно, но это не очень хорошо. Элемент с пустым ID [считается](https://stackoverflow.com/questions/6535934/is-an-id-allowed-to-be-empty-in-an-html-tag#:~:text=According%20to%20the%20W3C%3A) невалидным HTML

2023-10-01 18:02 UTC, tUnknownLegend commented on public/src/components/button/button.hbs
> +<button class="button {{class}}" type="{{type}}" id="{{id}}">
> в форме же используется type submit? 

все верно, решил уточнить, чтобы убедиться, что вы это понимаете)

2023-10-06 12:06 UTC, closed without merging