Pwa
frontend-park-mail-ru/2023_2_Potatiki pull request #20
Opened 2023-12-26 22:01 UTC by fitzplsr

2023-12-26 23:16 UTC, tUnknownLegend requested changes

2023-12-26 23:16 UTC, tUnknownLegend commented on manifest.json
> +
пустая строчка в конце (

2023-12-26 23:18 UTC, tUnknownLegend commented on manifest.json
> +
подлейте актуальный main еще

2023-12-26 23:49 UTC, fitzplsr commented on manifest.json
> +
а что не должно быть?

2023-12-27 01:21 UTC, tUnknownLegend commented on manifest.json
> +
ее нет к сожалению
![image](https://github.com/frontend-park-mail-ru/2023_2_Potatiki/assets/57019979/9b15e2dd-1270-4137-b06b-14c7a50b8bb8)

2023-12-27 01:21 UTC, tUnknownLegend commented on manifest.json
> +
вернее гитхаб считает, что ее нет из-за пробела видимо

2023-12-27 19:39 UTC, tUnknownLegend approved these changes

2023-12-27 19:39 UTC, merged