Potatiki 1.9. profile
frontend-park-mail-ru/2023_2_Potatiki pull request #8
Opened 2023-11-09 10:36 UTC by khristina455

2023-11-10 13:33 UTC, tUnknownLegend requested changes
Хорошая работа, но надо кое-что поправить. Много однотипных проблем во всем проекте - проверяйте везде, на каждое повторение коммент не писал

2023-11-10 13:33 UTC, tUnknownLegend commented on public/src/pages/orders-page/orders-page.js
> +        const header = new Header(this.#parent);
а зачем здесь хедер рендрить заново? Не очень понял, поясните, пожалуйста

2023-11-10 13:33 UTC, tUnknownLegend commented on public/src/pages/product-page/product-page.js
> +        const header = new Header(this.self);
видимо на каждой странице где нужен хедер вы его заново рендрите. Давайте не будем лишний раз перендривать. Эту логику можно вынести в базовый компонент страницы, например

2023-11-10 13:33 UTC, tUnknownLegend commented on public/src/stores/cart.js
> +    userAuth = this.userAuth.bind(this);
не очень понял зачем вам такое, у методов класса же и так есть this от класса. Поясните, пожалуйста

2023-11-10 13:33 UTC, tUnknownLegend commented on public/src/stores/cart.js
> +    userAuth = this.userAuth.bind(this);
но опять же это все должно быть в сторе юзера, а не корзины. К сущности корзины это никак не относится

2023-11-10 13:33 UTC, tUnknownLegend commented on public/src/stores/user.js
> +        isAuth: false,
так, у вас дублирование стейта в двух сторах) Вы можете просто обращаться к данным другого стора из этого, но не надо одно и тоже хранить. В профиле isAuth стоит оставить, а из корзины убрать. Это ко всем остальным сущностям, которые не должны быть в корзине тоже относится

2023-11-10 13:33 UTC, tUnknownLegend commented on public/src/components/signupForm/signupForm.js
> +        const el = this.phone.self;
давайте сделаем более понятные нейминги переменных ,потому что разобраться в том, что там происходит сейчас сложно(

2023-11-10 13:33 UTC, tUnknownLegend commented on public/src/components/signupForm/signupForm.js
> +        const el = this.phone.self;
еще можно подумать над тем, чтобы вынести это в отдельную функцию и возможно дальше деструктуризировать на подфункции и вынести их в utils

2023-11-10 13:33 UTC, tUnknownLegend commented on public/src/components/numberEditForm/numberEditForm.js
> +        const accept = new RegExp(el.dataset.accept || '\\d', 'g');
чувствую здесь копипасту с [signUpForm](https://github.com/frontend-park-mail-ru/2023_2_Potatiki/blob/5b4a836067b87c3fdb045bf7a74e5cbdf848af02/public/src/components/signupForm/signupForm.js#L169)
+ 1 причина это вынести в отдельные функции)

2023-11-10 13:33 UTC, tUnknownLegend commented on public/src/components/countManagement/count-management.js
давайте сделаем единообразный нейминг файлов во всем проекте. Если пишете camelCase - пишите его везде, если kebab-case - аналогично

2023-11-12 22:14 UTC, fitzplsr commented on public/src/components/orderResults/order-results.hbs
> +            <span class="order-results__sub-result-text" id="products-count">Товары</span>
это же окно где общая сумма заказа, оно всегда одно на странице

2023-11-13 07:13 UTC, tUnknownLegend commented on public/src/components/orderResults/order-results.hbs
> +            <span class="order-results__sub-result-text" id="products-count">Товары</span>
окей, я думал, что 

> это же окно где общая сумма заказа, оно всегда одно на странице

окей, тогда проблем нет. Подумал, что это карточка заказа

2023-11-13 08:01 UTC, tUnknownLegend commented on public/src/stores/user.js
> +    subscribeToEvents() {
подписываться на ивенты умеют только pages и components, stores так не могут(, это ломает логику flux

2023-11-13 08:15 UTC, tUnknownLegend commented on public/src/stores/user.js
> +    checkAuth() {
по-хорошему все приватные класс сделать приватными с точи зрения JS, чтобы не было их соблазна вызвать извне. Или хотя бы псевдо приватными, как писали раньше, т.е. _userLogout

2023-11-13 11:59 UTC, tUnknownLegend commented on public/src/stores/user.js
> +    subscribeToEvents() {
подписываться на события могут только views и components. Подписки в сторе на события ломают flux(

2023-11-13 13:00 UTC, tUnknownLegend requested changes
1. исправить комменты касательно стора
2. проверить, что нигде не осталось комментов (вроде везде почистили)
3. проверить, что обновленная версия работает на проде
4. исправлять другие комменты, если останется время

2023-11-13 15:14 UTC, merged